### PR TITLE
Add `logs` command for viewing the docker-compose logs

### PR DESCRIPTION
**Pull request by darrenmce**
simple interface to the `docker-compose logs -f` with the benefit of autocomplete

### CODE REVIEW

**Comment by mpareja** [comment]
I'm not sure we need this. I tend to just run `tt dc logs` which gives you all of the power of docker-compose. Thoughts?

**Comment by mpareja** [comment]
Sadly, this would also break 360insights usage of `logs` for bringing up Kibana. My finger muscle memory might be very upset!

**Comment by darrenmce** [comment]
ok lets revisit this if needed

**Comment by mpareja** [comment]
@darrenmce I actually just cherry-picked your first commit into master. I like that enhancement to the usage summary.

**Pull request closed without merging**
